### ISSUE TITLE
Upgrade to .NET Standard 2.x

### ISSUE THREAD

**Issue by Oceania2018** [alex-weaver/TensorSharp#6]
Hi Alex, this is a excellent library for tensor comuptation.
As we all know, `.net core` is the future. So is it possible to upgrade `TensorSharp`  to .NET Standard? If you don't have extra time, I could help. @alex-weaver

**Comment by alex-weaver** [comment]
@Oceania2018 `.net core` is absolutely the future. I don't have time to pick this up again right now, but I can't think of anything that's actually dependent on the full .NET Framework. It's pretty much a bunch of PInvoke calls and some array index shuffling, so hopefully it would be trivial to re-target. Pull requests are always appreciated :)

**Comment by Oceania2018** [comment]
Submitted a PR

**Comment by alex-weaver** [comment]
https://github.com/alex-weaver/TensorSharp/pull/7 merged. Thanks for the contribution!
